reddit:
  subreddits:
    - name: nootropics
      enabled: true
    - name: NootropicsDepot
      enabled: true
    - name: stackadvice
      enabled: true
    - name: biohackers
      enabled: true
    - name: supplements
      enabled: true
    - name: memory
      enabled: true
    - name: sleep
      enabled: true
    - name: steroids
      enabled: true
    - name: moreplatesmoredates
      enabled: true

twitter:
  queries:
    - q: '"stack" (nootropics OR biohacking) -is:retweet lang:en'
      enabled: true
    - q: '"cut stack" OR "bulk stack" -is:retweet lang:en'
      enabled: true
    - q: '"testosterone stack" OR "cycle support" -is:retweet lang:en'
      enabled: true

youtube:
  queries:
    - q: "nootropics stack"
      enabled: true
    - q: "anabolic stack"
      enabled: true
    - q: "cycle support stack"
      enabled: true

forums:
  feeds:
    - url: "https://www.reddit.com/r/steroids/.rss"
      enabled: true
    - url: "https://www.reddit.com/r/nootropics/.rss"
      enabled: true
